<a href="https://colab.research.google.com/github/ananthakrishnanpta/Data-processing_Numpy/blob/main/Assignment_PANDAS_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1) Generate an array of zeroes using inbuilt numpy function.

In [1]:
import numpy as np

a = np.zeros(3)
print(a)

[0. 0. 0.]


## 2) Run the given code and find the dot product of both arrays.

In [2]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[6 4 5 4]
 [4 4 4 9]
 [8 3 7 9]]
[[6 6 4]
 [6 5 4]
 [6 5 8]
 [4 3 3]]


In [3]:
a.dot(b)

array([[106,  93,  92],
       [108,  91,  91],
       [144, 125, 127]])

In [4]:
#Your code here
print(np.dot(a,b))


[[106  93  92]
 [108  91  91]
 [144 125 127]]


## 3)Read the csv file provided using pandas and display the first 5 entries

In [5]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/techis-ds-wiki/DS/Step 1-4 Data Processing/03_Assignment/data.csv')

Mounted at /content/drive


In [6]:
file1.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

## 4)Describe the data with all features.

In [7]:
file1.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

## 5)Find the total count of missing values for each feature.

In [9]:
print(file1.isnull().sum())

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64


## 6)Display all the unique values from the 'DESCRIPTION’ column.

In [10]:
file1.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

## 7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [30]:
file1.groupby('DESCRIPTION').apply(lambda dataframe: dataframe.mean(axis=1))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


DESCRIPTION              
Interpretive Center    8        8.873846
State Natural Area     16      60.459935
                       20      43.259877
State Nature Preserve  18      27.074837
                       19      22.576876
State Park             0      121.646320
                       1       59.244916
                       2      172.046260
                       3      191.704775
                       4      197.038719
                       5      191.356485
                       6      307.318430
                       7      110.604479
                       10    1304.882099
                       11      19.125880
                       14     161.863751
                       15     154.837672
                       23     122.974284
State Recreation Area  9        8.435126
                       12      17.349014
                       13      56.816504
                       17      11.951375
                       21     256.258575
                       22     1

## 8)Generate a random sample of 10 rows from the data.

In [16]:
file1.sample(10)


OBJECTID                              UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
2         23        Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                 Fort Ransom State Park  ...   0.000444   0.128733
13        36  Crow Flies High State Recreation Area  ...   0.000120   0.050518
18        39        Gunlogson State Nature Preserve  ...   0.000048   0.040465
21        43    Pembina Gorge State Recreation Area  ...   0.000615   0.338800
17        38    Fahlgren Park State Recreation Area  ...   0.000010   0.013294
20        41      Missouri River State Natural Area  ...   0.000083   0.087192
15        34              Lake Sakakawea State Park  ...   0.000357   0.191806
8         29    Lewis and Clark Interpretive Center  ...   0.000007   0.016774
16        37             Elkhorn State Natural Area  ...   0.000127   0.067082

[10 rows x 6 columns]

## 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [29]:
import random

New_feature = pd.Series(np.random.random(len(file1)))

# print(file1)
# print(New_feature)

file1['New_feature'] = New_feature
# file1 = file1.assign(New_feature = New_feature)
print(file1)
file1.to_csv("output_of_assignment.csv")

    OBJECTID  ... New_feature
0         21  ...    0.615674
1         22  ...    0.984384
2         23  ...    0.641035
3         24  ...    0.614700
4         25  ...    0.737582
5         26  ...    0.315251
6         27  ...    0.849205
7         28  ...    0.081721
8         29  ...    0.642449
9         30  ...    0.766231
10        31  ...    0.163605
11        32  ...    0.575352
12        35  ...    0.492951
13        36  ...    0.921883
14        33  ...    0.893159
15        34  ...    0.476197
16        37  ...    0.392465
17        38  ...    0.183571
18        39  ...    0.443672
19        40  ...    0.550462
20        41  ...    0.822108
21        43  ...    0.973462
22        44  ...    0.640900
23        45  ...    0.620889
24        42  ...    0.324894

[25 rows x 7 columns]


## 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [12]:
file1.OBJECTID.replace(0,file1.OBJECTID.mean())


0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64

In [13]:
file1.isna().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64